#!/usr/bin/env python3
"""Build the WORDS list for index.html.

- CLUES below is a curated map of common NYT crossword answers -> a definition
  written in authentic crossword-clue style (terse; abbr./fill-in markers; real
  proper-noun references).
- We order entries by real all-time NYT frequency (danvk.org data in
  freq_raw.txt: "WORD count" per line), most common first, so learners hit the
  highest-impact answers first. Words missing from the freq file sort last.
- Output is injected into index.html between the WORDS markers.
"""
import re, json, sys

CLUES = {
    # --- vowel-heavy core crosswordese (highest frequency) ---
    "ERA":  "Notable time period",
    "AREA": "Region; square footage",
    "ERE":  "Before, in verse",
    "ELI":  "Cotton gin inventor Whitney",
    "ONE":  "Number on a penny",
    "ALE":  "Pale ___ (pub brew)",
    "ORE":  "Vein contents",
    "ERIE": "Lake between Ohio and Ontario",
    "ALOE": "Burn-soothing plant",
    "ETA":  "Touchdown approx.",
    "ALI":  "'The Greatest' of boxing",
    "OLE":  "Cry at a bullfight",
    "ARE":  "'We ___ the champions'",
    "ESS":  "Curvy letter",
    "EDEN": "Garden of paradise",
    "ATE":  "Had a bite",
    "IRE":  "Wrath",
    "ARIA": "Diva's solo",
    "ANTE": "Poker pot starter",
    "ENE":  "Compass dir. between E and N",
    "ADO":  "Much ___ About Nothing",
    "ELSE": "'Or ___!'",
    "NEE":  "Maiden-name intro",
    "ACE":  "Serve that's untouched",
    "ALA":  "___ mode",
    "EEL":  "Sushi bar order",
    "ODE":  "Lyric poem",
    "ERR":  "Slip up",
    "EAR":  "Unit of corn",
    "END":  "Finale",
    "OREO": "Double Stuf cookie",
    "EST":  "NYC clock setting: Abbr.",
    "IDEA": "Lightbulb moment",
    "APE":  "Gorilla, e.g.; mimic",
    "AGE":  "Years lived",
    "IRA":  "Retirement acct.",
    "ASH":  "Fireplace residue",
    "SPA":  "Resort with mud baths",
    "ANT":  "Picnic pest",
    "ASEA": "Out on the ocean",
    "ANTI": "Opposed (to)",
    "EVE":  "Adam's mate",
    "ETNA": "Sicilian volcano",
    "ACRE": "43,560 square feet",
    "OLEO": "Butter substitute",
    "ANON": "Shortly, to a bard",
    "TAR":  "Sailor, in old slang",
    "SEE":  "'I ___ now'",
    "ARENA": "Concert venue",
    "EAT":  "Dig in",
    "ETE":  "Summer, in Cannes",
    "ASIA": "Largest continent",
    "ICE":  "Hockey surface",
    "EPEE": "Olympic fencing weapon",
    "ART":  "Museum display",
    "EON":  "Long, long time",
    "EGO":  "Self-importance",
    "ALEE": "Away from the wind",
    "ORAL": "Spoken, not written",
    "ONCE": "'___ upon a time'",
    "NET":  "Tennis divider",
    "EASE": "Relieve, as pain",
    "TSAR": "Pre-1917 Russian ruler",
    "ODOR": "Strong smell",
    "EROS": "Greek god of love",
    "TEN":  "Perfect gymnastics score",
    "AHA":  "'Gotcha!'",
    "SET":  "Ready, as a table",
    "IDOL": "American ___",
    "TEA":  "Earl Grey, e.g.",
    "EDIT": "Revise, as text",
    "ALEC": "Baldwin of '30 Rock'",
    "TNT":  "Blasting material",
    "STAR": "Hollywood celeb",
    "SEA":  "The briny deep",
    "RTE":  "Map line: Abbr.",
    "OSLO": "Norway's capital",
    "OMAR": "Sharif of 'Doctor Zhivago'",
    "LEI":  "Luau garland",
    "YES":  "Affirmative reply",
    "TREE": "Family ___",
    "ERASE": "Rub out",
    "EERIE": "Spooky",
    "OAR":  "Crew implement",
    "ERIN": "'___ go bragh'",
    "ISLE": "Capri, e.g.",
    "ELAN": "Flair; verve",
    "ALTO": "Voice below soprano",
    "USE":  "Put to work",
    "OTTO": "Bismarck's first name",
    "ECHO": "Canyon comeback",
    "ARES": "Greek god of war",
    "RIO":  "___ Grande",
    "NOR":  "Neither's partner",
    "IDO":  "Two words at the altar",
    "EDGE": "Slight advantage",
    "OBOE": "Orchestra woodwind",
    "OAT":  "Cheerios grain",
    "ECO":  "Green prefix",
    "EPA":  "Pollution-fighting org.",
    "ADE":  "Lemon ending",
    "ACHE": "Dull pain",
    "ROE":  "Fish eggs",
    "RARE": "Cooked just briefly",
    "IRAN": "Tehran's land",
    "AMEN": "'So be it'",
    "TOE":  "Sock's end",
    "ESP":  "Sixth sense, for short",
    "ELLA": "Fitzgerald of jazz",
    "ANNA": "Karenina of fiction",
    "AIR":  "Broadcast, as a show",
    "ADAM": "First man, in Genesis",
    "EAST": "Sunrise direction",
    "RNA":  "DNA cousin",
    "NEAT": "Served without ice",
    "AERO": "Flight-related prefix",
    "TIE":  "Deadlock",
    "SRO":  "Sellout sign: Abbr.",
    "REST": "Musical pause",
    "KNEE": "Joint above the shin",
    "ITEM": "Couple, in gossip",
    "INTO": "Really fond of",
    "STIR": "Mix with a spoon",
    "OVER": "Finished",
    "NEST": "Robin's roost",
    "EMIT": "Give off, as fumes",
    "ARID": "Bone-dry",
    "RED":  "In the ___ (losing money)",
    "ARC":  "Rainbow's shape",
    "ONTO": "Wise to",
    "ABLE": "Capable",
    "AXE":  "Lumberjack's tool",
    "UTE":  "Sport ___ (vehicle)",
    "LIE":  "Fib",
    "ENO":  "Brian who produced U2",
    "EMU":  "Flightless Aussie bird",
    "USER": "App customer",
    "SIR":  "Knight's title",
    "RENO": "Nevada gambling city",
    "RAT":  "Squealer",
    "IDLE": "Eric of Monty Python",
    "EWE":  "Ram's mate",
    "ELL":  "L-shaped building wing",
    "ASAP": "Pronto, in memos",
    "ARAB": "Purebred horse",
    "IRATE": "Hopping mad",
    "ETON": "British boys' school",
    "ORR":  "Bobby of the Bruins",
    "OMIT": "Leave out",
    "OIL":  "Squeaky wheel's need",
    "NEON": "Bright sign gas",
    "UTAH": "Salt Lake City's state",
    "URN":  "Coffee dispenser",
    "OMEN": "Sign of things to come",
    "ELM":  "Nightmare's street",
    "AURA": "Mystical glow",
    "ABE":  "Lincoln, familiarly",
    "NIL":  "Soccer score of zero",
    "LEA":  "Meadow, poetically",
    "ESAU": "Jacob's hairy twin",
    "OPAL": "October birthstone",
    "OLD":  "Not new",
    "ION":  "Charged particle",
    "EVER": "'Happily ___ after'",
    "APSE": "Church's altar end",
    "UNIT": "Inch or ounce",
    "OGRE": "Shrek, for one",
    "NEED": "Require",
    "EYE":  "Hurricane's center",
    "EVIL": "Wicked",
    "ALSO": "In addition",
    "OPERA": "Carmen, e.g.",
    "ATONE": "Make amends",
    "NERO": "Emperor who 'fiddled'",
    "IRENE": "'Goodnight ___'",
    "GAS":  "Car's fuel",
    "ENTER": "Key near Shift",
    "EGAD": "'Yikes!,' old-style",
    "EDNA": "'The Incredibles' designer Mode",
    "AFAR": "From ___ (at a distance)",
    "IRS":  "April tax org.",
    "IOTA": "Tiny bit",
    "INN":  "Roadside lodging",
    "ASP":  "Cleopatra's snake",
    "SAT":  "College entrance exam",
    "EURO": "Currency in Paris",
    "ATOP": "Resting on",
    "ATOM": "Tiny bit of matter",
    "ATM":  "Cash machine: Abbr.",
    "PSST": "'Hey, you!' (quietly)",
    "AWE":  "Shock and ___",
    "USA":  "Land of the free: Abbr.",
    "NTH":  "To the ___ degree",
    "ETC":  "And so on: Abbr.",
    "NEO":  "'The Matrix' hero",
    "ALAS": "'Woe is me!'",
    "STAT": "Pronto, in the ER",
    # --- a few learner-friendly classics rounding out the set ---
    "ANEW": "Once more",
    "AJAR": "Slightly open",
    "AVID": "Keen, as a fan",
    "ICON": "App symbol",
    "IGLOO": "Inuit dome home",
    "IMP":  "Little rascal",
    "ORCA": "Black-and-white whale",
    "OUST": "Drive from power",
    "OVAL": "Egg shape",
    "OWE":  "Be in debt",
    "OWL":  "Hooter of the night",
    "UNDO": "Reverse, as a deletion",
    "ELSA": "'Frozen' ice queen",
    "OBI":  "Kimono sash",
    "ESPN": "Sports cable channel",
    "NASA": "Moon-landing org.",
    "IBIS": "Long-billed wading bird",
    "ILK":  "Kind or sort",
    "IRK":  "Annoy",
    "EBB":  "Recede, as the tide",
    "ETCH": "Engrave, as glass",
    "ELO":  "Rock's ___ (Jeff Lynne band)",
    "OHIO": "Buckeye State",
    "OINK": "Pigpen sound",
}

# frequency rank lookup
rank = {}
try:
    with open("freq_raw.txt") as f:
        for i, line in enumerate(f):
            w = line.split()[0]
            if w not in rank:
                rank[w] = i
except FileNotFoundError:
    pass

BIG = 10**9
items = sorted(CLUES.items(), key=lambda kv: rank.get(kv[0], BIG))

# emit JS array
lines = []
for w, c in items:
    if '"' in c:
        sys.exit("double-quote in clue for %s; use single quotes" % w)
    lines.append('  {w:%s, c:%s},' % (json.dumps(w), json.dumps(c)))
js = "const WORDS = [\n" + "\n".join(lines) + "\n];"

html = open("index.html").read()
new = re.sub(r"const WORDS = \[.*?\n\];", js, html, count=1, flags=re.S)
if new == html:
    sys.exit("WORDS marker not found / unchanged")
open("index.html", "w").write(new)
print("words:", len(items))
print("with freq rank:", sum(1 for w in CLUES if w in rank), "/", len(CLUES))
print("missing from freq file (sorted last):", [w for w in CLUES if w not in rank])
